In [3]:
import pandas as pd
import numpy as np

import datetime

/Users/naoki/.pyenv/versions/3.6.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/Users/naoki/.pyenv/versions/3.6.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

In [2]:
h_trs = pd.read_csv("../input/historical_transactions.csv", usecols=["card_id", "purchase_date"], parse_dates=["purchase_date"])
n_trs = pd.read_csv("../input/new_merchant_transactions.csv", usecols=["card_id", "purchase_date"], parse_dates=["purchase_date"])

In [3]:
all_trs = pd.concat([h_trs, n_trs], axis=0).reset_index(drop=True)
all_trs.purchase_date = all_trs.purchase_date.apply(lambda x:x.date())

In [4]:
all_trs.head()

           card_id purchase_date
0  C_ID_4e6213e9bc    2017-06-25
1  C_ID_4e6213e9bc    2017-07-15
2  C_ID_4e6213e9bc    2017-08-09
3  C_ID_4e6213e9bc    2017-09-02
4  C_ID_4e6213e9bc    2017-03-10

second_active

In [5]:
all_trs["one"] = 1

In [6]:
df_purchase_pattern = all_trs.groupby("card_id")["purchase_date"].min().reset_index()
df_purchase_pattern.columns = ["card_id", "second_active_date"]

df_purchase_pattern["elapsed_second_absolute"] = (df_purchase_pattern.second_active_date - datetime.date(2010, 1, 1)).dt.days

In [7]:
df_purchase_pattern.head()

           card_id second_active_date  elapsed_second_absolute
0  C_ID_00007093c1         2017-02-14                     2601
1  C_ID_0001238066         2017-09-28                     2827
2  C_ID_0001506ef0         2017-01-14                     2570
3  C_ID_0001793786         2017-01-21                     2577
4  C_ID_000183fdda         2017-08-07                     2775

In [8]:
df_all_purchase = pd.pivot_table(all_trs, columns=["purchase_date"], index=["card_id"], values=["one"], aggfunc=sum, fill_value=0)
df_all_purchase.columns = [col[1] for col in df_all_purchase.columns.values]
df_all_purchase = df_all_purchase.reset_index()

In [9]:
df_all_purchase.head()

,card_id,2017-01-01,2017-01-02,2017-01-03,2017-01-04,2017-01-05,2017-01-06,2017-01-07,2017-01-08,2017-01-09,...,2018-04-21,2018-04-22,2018-04-23,2018-04-24,2018-04-25,2018-04-26,2018-04-27,2018-04-28,2018-04-29,2018-04-30
0,C_ID_00007093c1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,C_ID_0001238066,0,0,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,1,1
2,C_ID_0001506ef0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,C_ID_0001793786,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,C_ID_000183fdda,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1

In [10]:
third_active_date = [datetime.date(2010, 1, 1) for i in range(df_all_purchase.shape[0])]

for idx, r in df_all_purchase.iterrows():
    all_purcase_date_idx = np.where(r[1:]>0)[0] + 1
    if len(all_purcase_date_idx) >= 2:
        third_idx = all_purcase_date_idx[1]
    else:
        third_idx = all_purcase_date_idx[0]
    third_active_date[idx] = df_all_purchase.columns[third_idx]

In [11]:
df_third_active = pd.DataFrame({"card_id":df_all_purchase.card_id, "third_active_date":third_active_date})

In [12]:
df_purchase_pattern = pd.merge(df_purchase_pattern, df_third_active, on="card_id", how="outer")

In [13]:
df_purchase_pattern.head()

,card_id,second_active_date,elapsed_second_absolute,third_active_date
0,C_ID_00007093c1,2017-02-14,2601,2017-02-16
1,C_ID_0001238066,2017-09-28,2827,2017-09-29
2,C_ID_0001506ef0,2017-01-14,2570,2017-01-17
3,C_ID_0001793786,2017-01-21,2577,2017-02-01
4,C_ID_000183fdda,2017-08-07,2775,2017-08-21

In [14]:
df_purchase_pattern["elapsed_third_absolute"] = (df_purchase_pattern.third_active_date - datetime.date(2010, 1, 1)).dt.days

In [15]:
df_purchase_pattern["diff_second_and_third"] = (df_purchase_pattern.third_active_date - df_purchase_pattern.second_active_date).dt.days

In [16]:
purchase_freq = [0 for i in range(df_all_purchase.shape[0])]

for idx, r in df_all_purchase.iterrows():
    all_purcase_date_idx = np.where(r[1:]>0)[0] + 1
    if len(all_purcase_date_idx) >= 2:
        purchase_count = len(all_purcase_date_idx)
        
        top_idx = all_purcase_date_idx[0]
        end_idx = all_purcase_date_idx[-1]
        
        top_date = df_all_purchase.columns[top_idx]
        end_date = df_all_purchase.columns[end_idx]
        
        purchase_term = (end_date - top_date).days
        
        freq = 1.0 * purchase_term / purchase_count
    else:
        freq = 0
    purchase_freq[idx] = freq

In [17]:
df_purchase_freq = pd.DataFrame({"card_id":df_all_purchase.card_id, "purchase_freq":purchase_freq})

In [18]:
df_purchase_pattern = pd.merge(df_purchase_pattern, df_purchase_freq, on="card_id", how="outer")

In [19]:
df_purchase_pattern.head()

,card_id,second_active_date,elapsed_second_absolute,third_active_date,elapsed_third_absolute,diff_second_and_third,purchase_freq
0,C_ID_00007093c1,2017-02-14,2601,2017-02-16,2603,2,5.048193
1,C_ID_0001238066,2017-09-28,2827,2017-09-29,2828,1,2.459770
2,C_ID_0001506ef0,2017-01-14,2570,2017-01-17,2573,3,9.391304
3,C_ID_0001793786,2017-01-21,2577,2017-02-01,2588,11,3.510204
4,C_ID_000183fdda,2017-08-07,2775,2017-08-21,2789,14,3.057471

In [20]:
df_all_purchase

,card_id,2017-01-01,2017-01-02,2017-01-03,2017-01-04,2017-01-05,2017-01-06,2017-01-07,2017-01-08,2017-01-09,...,2018-04-21,2018-04-22,2018-04-23,2018-04-24,2018-04-25,2018-04-26,2018-04-27,2018-04-28,2018-04-29,2018-04-30
0,C_ID_00007093c1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,C_ID_0001238066,0,0,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,1,1
2,C_ID_0001506ef0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,C_ID_0001793786,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,C_ID_000183fdda,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
5,C_ID_00024e244b,0,2,0,1,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
6,C_ID_0002709b5a,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
7,C_ID_00027503e2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,C_ID_000298032a,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,C_ID_0002ba3c2e,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,C_ID_0002c7c2c1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,C_ID_00032df08f,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,C_ID_0003754056,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,C_ID_000377f6a0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,C_ID_0003be3c83,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,C_ID_0003f41435,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,C_ID_00042d509c,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,C_ID_0004587331,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,C_ID_0004725b87,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,2,0,0,0,0
19,C_ID_0004888ddd,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,C_ID_0004b68c49,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,C_ID_0004c2a5ab,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,C_ID_00057b99fe,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,C_ID_000599daf9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
24,C_ID_0005b2f279,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,C_ID_0005b5804f,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,C_ID_0005f16cc8,0,2,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,C_ID_0006152db8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,C_ID_000616f4a8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,C_ID_000664aa02,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325510,C_ID_fffb79fb56,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
325511,C_ID_fffb9ea3f6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
325512,C_ID_fffba72dc5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
325513,C_ID_fffbdf036b,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
325514,C_ID_fffbee5c24,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
325515,C_ID_fffc96bf24,1,2,4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
325516,C_ID_fffcb74f49,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
325517,C_ID_fffcf66e12,0,0,0,0,0,0,0,2,0,...,0,0,0,0,0,0,0,0,0,0
325518,C_ID_fffd070e0e,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
325519,C_ID_fffd1207a8,1,1,1,1,4,3,2,4,2,...,1,0,0,0,0,1,0,0,0,1
325520,C_ID_fffd24dcf3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,2,1,1,0,0
325521,C_ID_fffd337484,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
325522,C_ID_fffd345048,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
325523,C_ID_fffd351e7f,0,0,0,0,0,0,0,0,0,...,0,0,1,0,3,2,0,0,0,0
325524,C_ID_fffd93c8bf,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,0,1
325525,C_ID_fffd943b91,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
325526,C_ID_fffdad8aa0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,0,0,0
325527,C_ID_fffde15ab6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
325528,C_ID_fffdf34798,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,0,0
325529,C_ID_fffe29a04a,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
325530,C_ID_fffe78b232,0,0,0,1,4,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
325531,C_ID_fffe866457,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,1
325532,C_ID_fffea6de74,0,0,0,0,0,0,0,0,0,...,2,0,0,0,0,0,1,0,0,0
325533,C_ID_fffeced303,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
325534,C_ID_fffeed3a89,0,0,0,0,0,0,0,0,0,...,2,2,0,2,1,1,0,4,2,2
325535,C_ID_ffff1d9928,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
325536,C_ID_ffff579d3a,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
325537,C_ID_ffff756266,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
325538,C_ID_ffff828181,0,0,0,0,1,2,0,0,0,...,0,0,0,0,0,0,0,1,2,0
325539,C_ID_fffffd5772,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [21]:
list_purchase_term = [0 for i in range(df_all_purchase.shape[0])]

for idx, r in df_all_purchase.iterrows():
    all_purcase_date_idx = np.where(r[1:]>0)[0] + 1
        
    top_idx = all_purcase_date_idx[0]
    end_idx = all_purcase_date_idx[-1]
        
    top_date = df_all_purchase.columns[top_idx]
    end_date = df_all_purchase.columns[end_idx]
        
    purchase_term = (end_date - top_date).days
    
    list_purchase_term[idx] = purchase_term

In [22]:
df_purchase_term = pd.DataFrame({"card_id":df_all_purchase.card_id, "purchase_term":list_purchase_term})

In [23]:
df_purchase_pattern = pd.merge(df_purchase_pattern, df_purchase_term, on="card_id", how="outer")

In [24]:
df_purchase_pattern.head()

,card_id,second_active_date,elapsed_second_absolute,third_active_date,elapsed_third_absolute,diff_second_and_third,purchase_freq,purchase_term
0,C_ID_00007093c1,2017-02-14,2601,2017-02-16,2603,2,5.048193,419
1,C_ID_0001238066,2017-09-28,2827,2017-09-29,2828,1,2.459770,214
2,C_ID_0001506ef0,2017-01-14,2570,2017-01-17,2573,3,9.391304,432
3,C_ID_0001793786,2017-01-21,2577,2017-02-01,2588,11,3.510204,344
4,C_ID_000183fdda,2017-08-07,2775,2017-08-21,2789,14,3.057471,266

In [25]:
df_all_purchase.columns[335:397]

Index([2017-12-01, 2017-12-02, 2017-12-03, 2017-12-04, 2017-12-05, 2017-12-06,
       2017-12-07, 2017-12-08, 2017-12-09, 2017-12-10, 2017-12-11, 2017-12-12,
       2017-12-13, 2017-12-14, 2017-12-15, 2017-12-16, 2017-12-17, 2017-12-18,
       2017-12-19, 2017-12-20, 2017-12-21, 2017-12-22, 2017-12-23, 2017-12-24,
       2017-12-25, 2017-12-26, 2017-12-27, 2017-12-28, 2017-12-29, 2017-12-30,
       2017-12-31, 2018-01-01, 2018-01-02, 2018-01-03, 2018-01-04, 2018-01-05,
       2018-01-06, 2018-01-07, 2018-01-08, 2018-01-09, 2018-01-10, 2018-01-11,
       2018-01-12, 2018-01-13, 2018-01-14, 2018-01-15, 2018-01-16, 2018-01-17,
       2018-01-18, 2018-01-19, 2018-01-20, 2018-01-21, 2018-01-22, 2018-01-23,
       2018-01-24, 2018-01-25, 2018-01-26, 2018-01-27, 2018-01-28, 2018-01-29,
       2018-01-30, 2018-01-31],
      dtype='object')

In [26]:
df_purchase_pattern ["purchase_count_201712_201801"] = np.sum(df_all_purchase[df_all_purchase.columns[335:397]].values, axis=1)

In [27]:
df_purchase_pattern["purchase_count_201001_201711"] = np.sum(df_all_purchase[df_all_purchase.columns[1:335]].values, axis=1)

In [28]:
df_purchase_pattern["purchase_count_201802_201804"] = np.sum(df_all_purchase[df_all_purchase.columns[397:]].values, axis=1)

In [29]:
df_purchase_pattern = df_purchase_pattern.drop("third_active_date", axis=1)

In [30]:
# df_purchase_pattern.to_csv("../input/purchase_pattern.csv", index=False)

In [31]:
value_1 = df_purchase_pattern.diff_second_and_third.values
value_2 = df_purchase_pattern.purchase_freq.values

In [32]:
np.corrcoef(value_1, value_2)[0,1]

0.4597754627321218

In [33]:
from sklearn.decomposition import NMF
sparse_matrix = df_all_purchase[df_all_purchase.columns[1:]].values

N_COMP =10
model = NMF(n_components=N_COMP, init='random', random_state=0) 
embedded = model.fit_transform(sparse_matrix)

df = pd.DataFrame(embedded, columns=["NMF_comp_purchase_{}".format(i) for i in range(1,N_COMP+1)])
df["card_id"] = df_all_purchase.card_id.values
# df.to_csv("../input/purchase_pettern_nmf.csv", index=False)

In [4]:
h_trs = pd.read_csv("../input/historical_transactions.csv", usecols=["card_id", "purchase_amount", "purchase_date"], parse_dates=["purchase_date"])
n_trs = pd.read_csv("../input/new_merchant_transactions.csv", usecols=["card_id", "purchase_amount", "purchase_date"], parse_dates=["purchase_date"])

In [5]:
all_trs = pd.concat([h_trs, n_trs], axis=0).reset_index(drop=True)
all_trs.purchase_date = all_trs.purchase_date.apply(lambda x:x.date())

In [6]:
np.min(all_trs.purchase_amount)

-0.7469078

In [7]:
all_trs.purchase_amount = np.log(all_trs.purchase_amount + 100)

In [8]:
df_all_purchase_amount = pd.pivot_table(all_trs, columns=["purchase_date"], index=["card_id"], values=["purchase_amount"], aggfunc=sum, fill_value=0)
df_all_purchase_amount.columns = [col[1] for col in df_all_purchase_amount.columns.values]
df_all_purchase_amount = df_all_purchase_amount.reset_index()

In [9]:
df_all_purchase_amount

,card_id,2017-01-01,2017-01-02,2017-01-03,2017-01-04,2017-01-05,2017-01-06,2017-01-07,2017-01-08,2017-01-09,...,2018-04-21,2018-04-22,2018-04-23,2018-04-24,2018-04-25,2018-04-26,2018-04-27,2018-04-28,2018-04-29,2018-04-30
0,C_ID_00007093c1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,C_ID_0001238066,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.598443,4.599486,4.597962,0.000000,0.000000,0.000000,0.000000,0.000000,4.601451,4.600749
2,C_ID_0001506ef0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,C_ID_0001793786,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,C_ID_000183fdda,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,4.598218,0.000000,0.000000,0.000000,4.604093
5,C_ID_00024e244b,0.000000,9.195868,0.000000,4.597794,0.000000,0.000000,0.000000,0.000000,9.195728,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,C_ID_0002709b5a,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.599035
7,C_ID_00027503e2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,C_ID_000298032a,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,C_ID_0002ba3c2e,0.000000,0.000000,0.000000,0.000000,0.000000,4.598632,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,C_ID_0002c7c2c1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,C_ID_00032df08f,0.000000,0.000000,0.000000,0.000000,4.601298,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12,C_ID_0003754056,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
13,C_ID_000377f6a0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,C_ID_0003be3c83,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15,C_ID_0003f41435,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
16,C_ID_00042d509c,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
17,C_ID_0004587331,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,C_ID_0004725b87,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.603711,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,9.197918,0.000000,0.000000,0.000000,0.000000
19,C_ID_0004888ddd,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,C_ID_0004b68c49,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
21,C_ID_0004c2a5ab,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,C_ID_00057b99fe,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23,C_ID_000599daf9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.597900,0.000000,0.000000,0.000000
24,C_ID_0005b2f279,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25,C_ID_0005b5804f,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
26,C_ID_0005f16cc8,0.000000,9.196073,0.000000,0.000000,4.597915,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
27,C_ID_0006152db8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
28,C_ID_000616f4a8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
29,C_ID_000664aa02,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325510,C_ID_fffb79fb56,0.000000,0.000000,4.603013,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
325511,C_ID_fffb9ea3f6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
325512,C_ID_fffba72dc5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
325513,C_ID_fffbdf036b,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
325514,C_ID_fffbee5c24,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
325515,C_ID_fffc96bf24,4.597840,9.195615,18.440976,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
325516,C_ID_fffcb74f49,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,4.598808,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
325517,C_ID_fffcf66e12,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.196617,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
325518,C_ID_fffd070e0e,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,4.632633,0.000000,0.000000,0.000000,0.000000
325519,C_ID_fffd1207a8,4.597991,4.598259,4.597953,4.598084,18.391472,13.793596,9.195937,18.391597,9.195815,...,4.598644,0.000000,0.000000,0.000000,0.000000,4.599790,0.000000,0.000000,0.000000,4.599310
325520,C_ID_fffd24dcf3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,9.204828,4.598566,4.600904,0.000000,0.000000
325521,C_ID_fffd337484,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
325522,C_ID_fffd345048,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.598203,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
325523,C_ID_fffd351e7f,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,4.597976,0.000000,13.794332,9.196957,0.000000,0.000000,0.000000,0.000000
325524,C_ID_fffd93c8bf,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.200838,0.000000,4.599783
325525,C_ID_fffd943b91,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
325526,C_ID_fffdad8aa0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,9.195613,0.000000,0.000000,0.000000,0.000000,0.000000
325527,C_ID_fffde15ab6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
325528,C_ID_fffdf34798,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,9.196390,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
325529,C_ID_fffe29a04a,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
325530,C_ID_fffe78b232,0.000000,0.000000,0.000000,4.598732,18.397539,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.599534,0.000000,0.000000,0.000000
325531,C_ID_fffe866457,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.598191,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.605785,0.000000,4.598173
325532,C_ID_fffea6de74,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9.196688,0.000000,0.000000,0.000000,0.000000,0.000000,4.598335,0.000000,0.000000,0.000000
325533,C_ID_fffeced303,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.598067,0.000000,0.000000,0.000000
325534,C_ID_fffeed3a89,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9.196225,9.195884,0.000000,9.197005,4.597855,4.624560,0.000000,18.393321,9.196690,9.196756
325535,C_ID_ffff1d9928,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
325536,C_ID_ffff579d3a,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
325537,C_ID_ffff756266,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
325538,C_ID_ffff828181,0.000000,0.000000,0.000000,0.000000,4.601828,9.202705,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.599256,9.199716,0.000000
325539,C_ID_fffffd5772,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [10]:
from sklearn.decomposition import NMF
sparse_matrix = df_all_purchase_amount[df_all_purchase_amount.columns[1:]].values

N_COMP =10
model = NMF(n_components=N_COMP, init='random', random_state=0) 
embedded = model.fit_transform(sparse_matrix)

df = pd.DataFrame(embedded, columns=["NMF_comp_purchase_amount_{}".format(i) for i in range(1,N_COMP+1)])
df["card_id"] = df_all_purchase_amount.card_id.values

In [11]:
df

,NMF_comp_purchase_amount_1,NMF_comp_purchase_amount_2,NMF_comp_purchase_amount_3,NMF_comp_purchase_amount_4,NMF_comp_purchase_amount_5,NMF_comp_purchase_amount_6,NMF_comp_purchase_amount_7,NMF_comp_purchase_amount_8,NMF_comp_purchase_amount_9,NMF_comp_purchase_amount_10,card_id
0,0.721066,1.829483,0.000000,0.815564,0.332998,0.707339,0.478885,1.142149,0.442798,0.059455,C_ID_00007093c1
1,3.037685,0.000000,1.625180,0.318512,0.000000,0.294300,1.076796,0.000000,0.000000,1.452770,C_ID_0001238066
2,0.172216,0.048791,0.951375,0.000000,0.420026,0.880144,0.082123,0.080670,0.000000,0.143952,C_ID_0001506ef0
3,2.990321,4.503387,0.143557,0.000000,0.888344,0.000000,0.000000,1.538570,2.032450,0.214066,C_ID_0001793786
4,0.391702,0.000000,0.668648,0.714809,0.000000,1.032217,1.457717,0.000000,1.189583,0.389047,C_ID_000183fdda
5,0.000000,1.678928,0.000000,0.032561,0.450004,0.412933,0.108725,0.000000,0.318982,0.057423,C_ID_00024e244b
6,2.364196,0.818926,0.471910,0.000000,0.000000,0.186665,0.217067,0.282880,0.223997,0.272550,C_ID_0002709b5a
7,0.980403,1.266068,0.000000,0.157907,0.000000,0.159327,0.035909,0.132449,0.149534,0.105473,C_ID_00027503e2
8,0.889370,0.298452,0.000000,0.000000,0.201055,0.000000,0.172068,0.068219,0.041020,0.236723,C_ID_000298032a
9,0.000000,2.396371,0.122776,0.350204,0.496971,0.000000,0.000000,0.000000,0.536260,0.000000,C_ID_0002ba3c2e
10,1.255335,0.802641,1.263231,0.000000,0.000000,0.129936,0.061658,0.342852,0.050870,0.256812,C_ID_0002c7c2c1
11,1.163616,1.238894,0.554744,0.000000,0.623479,0.030404,0.085295,0.978798,1.486875,0.000000,C_ID_00032df08f
12,0.493254,0.748280,0.135787,0.120069,0.000000,0.273488,0.000000,0.193674,0.075990,0.022836,C_ID_0003754056
13,0.229390,0.000000,0.008943,0.000000,0.067118,0.603648,0.000000,0.000000,0.000000,0.522211,C_ID_000377f6a0
14,0.025001,1.019982,2.905924,0.000000,0.000000,0.883741,0.414203,0.000000,2.057434,0.000000,C_ID_0003be3c83
15,0.874333,8.457425,0.000000,0.000000,0.000000,1.629369,1.018886,0.070462,1.205754,0.428519,C_ID_0003f41435
16,5.390774,0.256117,0.205859,0.686874,0.000000,0.434129,0.000000,0.000000,0.000000,0.098813,C_ID_00042d509c
17,0.000000,0.000000,0.000000,0.106811,0.000000,0.000000,0.247940,0.000000,0.068689,0.225962,C_ID_0004587331
18,0.852419,0.585336,0.469304,0.026633,0.406176,0.344587,0.001314,0.326070,0.454312,0.141059,C_ID_0004725b87
19,0.509857,1.600962,0.187671,0.185842,0.000000,0.183749,0.001655,0.000000,0.190125,0.000000,C_ID_0004888ddd
20,0.000000,0.000000,0.102489,0.078666,0.000000,0.000000,0.016668,0.000000,0.039087,0.101930,C_ID_0004b68c49
21,0.499071,0.601527,0.552296,0.000000,0.875748,0.150528,0.113950,0.281007,0.080681,0.000000,C_ID_0004c2a5ab
22,0.882862,0.117095,0.232846,0.000000,0.107905,0.000000,0.214595,0.302343,0.007656,0.000000,C_ID_00057b99fe
23,2.909093,0.542218,0.000000,0.000000,0.045594,0.164572,0.105573,0.079753,0.000000,0.000000,C_ID_000599daf9
24,0.009324,0.134717,0.268683,0.000000,0.073743,0.000000,0.000000,0.033704,0.046636,0.096766,C_ID_0005b2f279
25,0.487665,0.165589,0.000000,0.456599,0.000000,0.000000,0.024642,0.000000,0.000000,0.000618,C_ID_0005b5804f
26,3.002324,0.323922,1.204319,0.000000,0.805688,0.270934,0.907893,0.046723,0.989255,0.000000,C_ID_0005f16cc8
27,0.006340,1.081620,1.879483,0.000000,0.000000,0.312164,0.203928,0.000000,0.367341,0.000000,C_ID_0006152db8
28,0.000000,0.000000,0.247987,0.018546,0.192089,0.022784,0.000000,0.000000,0.807982,0.111689,C_ID_000616f4a8
29,0.000000,0.000000,0.325382,0.000000,0.000000,0.000000,0.445999,0.000000,0.000000,0.733251,C_ID_000664aa02
...,...,...,...,...,...,...,...,...,...,...,...
325510,0.000000,0.000000,0.000000,0.000000,0.339759,0.001797,0.000000,0.289509,0.000000,0.000000,C_ID_fffb79fb56
325511,0.000000,1.648528,0.000000,0.000000,0.003888,0.000000,0.968333,0.000000,0.000000,0.349931,C_ID_fffb9ea3f6
325512,2.130801,0.000000,1.217346,0.000000,0.000000,1.314270,0.189935,0.000000,0.000000,0.363168,C_ID_fffba72dc5
325513,0.000000,0.000000,0.000000,0.000000,0.926311,0.000000,0.000000,2.564848,0.000000,0.000000,C_ID_fffbdf036b
325514,0.000000,0.306854,0.306091,0.020219,0.005035,0.198399,0.000000,0.180082,0.029417,0.017088,C_ID_fffbee5c24
325515,2.377501,1.656325,0.000000,0.518507,1.327901,0.609836,0.858072,1.060041,0.965143,0.315749,C_ID_fffc96bf24
325516,1.764088,1.059415,1.092233,0.000000,0.000000,0.670095,0.840223,0.000000,0.300920,0.148849,C_ID_fffcb74f49
325517,0.827149,0.000000,0.000960,0.090565,0.269953,0.000000,0.107474,0.121843,0.088235,0.249423,C_ID_fffcf66e12
325518,0.921497,0.942408,0.000000,0.432273,0.136519,0.176643,0.309958,0.051195,0.000000,0.000000,C_ID_fffd070e0e
325519,6.231995,8.118824,6.166351,0.115425,5.802811,1.245040,2.726453,2.457369,1.610853,0.806161,C_ID_fffd1207a8
325520,0.657066,0.098999,0.051086,0.000000,0.000000,0.141974,0.045677,0.038563,0.071822,0.000000,C_ID_fffd24dcf3
325521,0.000000,0.703367,0.000000,0.252527,0.137796,0.000000,0.000000,0.414264,0.146228,0.000000,C_ID_fffd337484
325522,0.000000,0.968864,0.011384,0.000000,0.005647,0.076200,0.977051,0.000000,0.685330,0.199781,C_ID_fffd345048
325523,4.660797,2.178411,0.318096,0.977731,0.000000,0.922130,1.847244,1.345167,0.384382,0.464937,C_ID_fffd351e7f
325524,6.865963,0.000000,1.178144,0.038409,0.000000,0.000000,0.409543,0.000000,0.618816,1.067677,C_ID_fffd93c8bf
325525,0.181477,0.612582,0.020762,0.000000,0.079216,0.000000,0.193619,0.496911,0.755100,0.000000,C_ID_fffd943b91
325526,7.205648,0.000000,1.103404,0.050174,0.000000,0.970582,1.141910,0.000000,0.000000,0.000000,C_ID_fffdad8aa0
325527,0.720460,1.897428,0.118645,0.177011,0.000000,0.136035,0.084700,0.059393,0.938974,0.000000,C_ID_fffde15ab6
325528,0.000000,1.436871,0.000000,0.058761,0.002133,0.006543,0.708390,0.000000,0.222506,0.122807,C_ID_fffdf34798
325529,0.129435,0.418994,0.216265,0.000000,0.000000,0.036259,0.810676,0.670476,0.002754,0.754134,C_ID_fffe29a04a
325530,9.946688,2.647318,0.000000,0.045627,1.713198,0.235961,1.708356,2.291371,1.488648,0.003279,C_ID_fffe78b232
325531,0.815448,0.000000,0.085373,0.000000,0.011005,0.402753,0.981007,0.002515,0.000000,0.453540,C_ID_fffe866457
325532,4.373810,3.620796,2.632622,1.117725,0.000000,1.269550,3.509459,0.168826,1.236793,2.002910,C_ID_fffea6de74
325533,4.575235,1.511920,1.412445,0.000000,0.000000,0.099655,0.768301,0.889747,1.151469,0.108099,C_ID_fffeced303
325534,0.000000,0.000000,0.792085,0.009199,0.000000,0.000000,3.457710,0.000000,0.000000,2.180049,C_ID_fffeed3a89
325535,0.660712,0.000000,0.000000,0.000000,0.000000,0.052207,0.089555,0.000000,0.002951,0.110226,C_ID_ffff1d9928
325536,0.367833,0.750889,0.000000,0.000000,0.000000,0.275072,0.461063,0.000000,1.927682,0.543753,C_ID_ffff579d3a
325537,0.000000,0.000000,0.016490,0.577606,0.198221,0.000000,0.000000,0.103511,0.183170,0.000000,C_ID_ffff756266
325538,2.269415,1.164921,0.356543,0.876272,1.042811,0.561576,0.506183,0.708557,0.985517,0.530307,C_ID_ffff828181
325539,1.900586,0.000000,0.199274,0.036710,0.000000,0.505755,0.936745,0.000000,0.331478,0.443205,C_ID_fffffd5772

In [12]:
df.to_csv("../input/purchase_amount_pettern_nmf.csv", index=False)