In [50]:
import os
from collections import defaultdict
from csv import DictReader
import math

import numpy as np
import pandas as pd

In [51]:
usecols = [
    "card_id",
    "merchant_id",
    "category_1", 
    "category_2",
    "category_3"
]

In [52]:
h_trs = pd.read_csv("../input/historical_transactions.csv", usecols=usecols)
n_trs = pd.read_csv("../input/new_merchant_transactions.csv", usecols=usecols)
merchants = pd.read_csv("../input/merchants.csv")

In [53]:
trs = pd.concat([h_trs, n_trs], axis=0).reset_index(drop=True)

In [56]:
trs_category = pd.merge(
    trs, 
    merchants[["merchant_id", "category_4"]], 
    on="merchant_id", 
    how="left"
)[["card_id", "category_1",  "category_2", "category_3", "category_4"]]

In [59]:
trs_category_dummy = pd.get_dummies(data=trs_category, columns=["category_1", "category_2", "category_3", "category_4"])
trs_category_dummy

,card_id,category_1_N,category_1_Y,category_2_1.0,category_2_2.0,category_2_3.0,category_2_4.0,category_2_5.0,category_3_A,category_3_B,category_3_C,category_4_N,category_4_Y
0,C_ID_4e6213e9bc,1,0,1,0,0,0,0,1,0,0,0,1
1,C_ID_4e6213e9bc,1,0,1,0,0,0,0,1,0,0,0,1
2,C_ID_4e6213e9bc,1,0,1,0,0,0,0,1,0,0,0,1
3,C_ID_4e6213e9bc,1,0,1,0,0,0,0,1,0,0,0,1
4,C_ID_4e6213e9bc,1,0,1,0,0,0,0,1,0,0,0,1
5,C_ID_4e6213e9bc,1,0,1,0,0,0,0,1,0,0,1,0
6,C_ID_4e6213e9bc,1,0,1,0,0,0,0,1,0,0,0,1
7,C_ID_4e6213e9bc,1,0,1,0,0,0,0,1,0,0,1,0
8,C_ID_4e6213e9bc,1,0,1,0,0,0,0,1,0,0,0,1
9,C_ID_4e6213e9bc,1,0,1,0,0,0,0,1,0,0,0,1
10,C_ID_4e6213e9bc,1,0,1,0,0,0,0,1,0,0,0,1
11,C_ID_4e6213e9bc,1,0,0,0,0,0,0,1,0,0,1,0
12,C_ID_4e6213e9bc,1,0,1,0,0,0,0,1,0,0,0,1
13,C_ID_4e6213e9bc,1,0,1,0,0,0,0,1,0,0,0,1
14,C_ID_4e6213e9bc,1,0,1,0,0,0,0,1,0,0,0,1
15,C_ID_4e6213e9bc,1,0,1,0,0,0,0,1,0,0,0,1
16,C_ID_4e6213e9bc,1,0,1,0,0,0,0,1,0,0,0,1
17,C_ID_4e6213e9bc,1,0,1,0,0,0,0,1,0,0,0,1
18,C_ID_4e6213e9bc,1,0,1,0,0,0,0,1,0,0,0,1
19,C_ID_4e6213e9bc,1,0,1,0,0,0,0,1,0,0,1,0
20,C_ID_4e6213e9bc,1,0,1,0,0,0,0,1,0,0,0,1
21,C_ID_4e6213e9bc,1,0,1,0,0,0,0,1,0,0,0,1
22,C_ID_4e6213e9bc,1,0,1,0,0,0,0,1,0,0,0,1
23,C_ID_4e6213e9bc,1,0,1,0,0,0,0,1,0,0,0,1
24,C_ID_4e6213e9bc,1,0,1,0,0,0,0,1,0,0,0,1
25,C_ID_4e6213e9bc,1,0,1,0,0,0,0,1,0,0,1,0
26,C_ID_4e6213e9bc,1,0,1,0,0,0,0,1,0,0,1,0
27,C_ID_4e6213e9bc,1,0,1,0,0,0,0,1,0,0,0,1
28,C_ID_4e6213e9bc,1,0,1,0,0,0,0,1,0,0,0,1
29,C_ID_4e6213e9bc,1,0,1,0,0,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32328645,C_ID_69f1f3ebe6,1,0,1,0,0,0,0,1,0,0,0,1
32328646,C_ID_df4e6d6000,1,0,1,0,0,0,0,0,0,0,1,0
32328647,C_ID_1237c3fdc8,1,0,0,1,0,0,0,1,0,0,1,0
32328648,C_ID_f992de33d6,1,0,0,0,0,0,0,1,0,0,1,0
32328649,C_ID_e81ed766f7,1,0,1,0,0,0,0,0,1,0,1,0
32328650,C_ID_b77af92f06,1,0,0,0,1,0,0,0,1,0,1,0
32328651,C_ID_abe7761316,1,0,1,0,0,0,0,0,0,1,0,1
32328652,C_ID_734044eeeb,1,0,0,0,0,1,0,0,0,0,0,1
32328653,C_ID_1e2c41f86e,1,0,0,0,0,1,0,1,0,0,0,1
32328654,C_ID_737e5c1d9f,1,0,0,0,1,0,0,1,0,0,0,1
32328655,C_ID_28a5007fc6,0,1,0,0,0,0,0,0,1,0,0,1
32328656,C_ID_a491e3dced,1,0,1,0,0,0,0,0,0,1,1,0
32328657,C_ID_475e1a530f,1,0,1,0,0,0,0,0,1,0,0,1
32328658,C_ID_ef391c6cec,1,0,1,0,0,0,0,1,0,0,1,0
32328659,C_ID_06512aaeca,1,0,1,0,0,0,0,1,0,0,0,1
32328660,C_ID_c0c1724034,1,0,0,0,0,1,0,0,1,0,0,1
32328661,C_ID_bb36dec90b,1,0,1,0,0,0,0,1,0,0,1,0
32328662,C_ID_8dedf7350a,1,0,1,0,0,0,0,0,1,0,1,0
32328663,C_ID_5aa521bb3e,0,1,0,0,0,0,0,0,0,1,0,1
32328664,C_ID_c07707ff74,1,0,0,0,0,0,1,0,0,1,1,0
32328665,C_ID_c0dda9d36b,1,0,0,0,1,0,0,0,1,0,0,1
32328666,C_ID_01d35d1005,1,0,1,0,0,0,0,1,0,0,1,0
32328667,C_ID_611d4d588f,1,0,0,0,1,0,0,0,1,0,1,0
32328668,C_ID_0509e85404,1,0,0,0,1,0,0,0,1,0,1,0
32328669,C_ID_d3ad1091dc,1,0,1,0,0,0,0,1,0,0,1,0
32328670,C_ID_1320dee851,1,0,0,0,1,0,0,1,0,0,1,0
32328671,C_ID_f112aa3381,1,0,1,0,0,0,0,1,0,0,0,1
32328672,C_ID_bd97b86450,1,0,1,0,0,0,0,0,1,0,0,1
32328673,C_ID_c0513fd84f,1,0,0,0,1,0,0,1,0,0,1,0
32328674,C_ID_a935410f8e,1,0,1,0,0,0,0,1,0,0,1,0

In [63]:
trs_category_dummy.columns

Index(['card_id', 'category_1_N', 'category_1_Y', 'category_2_1.0',
       'category_2_2.0', 'category_2_3.0', 'category_2_4.0', 'category_2_5.0',
       'category_3_A', 'category_3_B', 'category_3_C', 'category_4_N',
       'category_4_Y'],
      dtype='object')

In [67]:
agg_func = {
    'category_1_N': ["sum", "mean", "std"], 
    'category_1_Y': ["sum", "mean", "std"], 
    'category_2_1.0': ["sum", "mean", "std"],
    'category_2_2.0': ["sum", "mean", "std"], 
    'category_2_3.0': ["sum", "mean", "std"], 
    'category_2_4.0': ["sum", "mean", "std"], 
    'category_2_5.0': ["sum", "mean", "std"],
    'category_3_A': ["sum", "mean", "std"], 
    'category_3_B': ["sum", "mean", "std"], 
    'category_3_C': ["sum", "mean", "std"], 
    'category_4_N': ["sum", "mean", "std"],
    'category_4_Y': ["sum", "mean", "std"]
}

trs_category_summary = trs_category_dummy.groupby("card_id").agg(agg_func)

In [70]:
trs_category_summary.columns = ["_".join(i).strip() for i in trs_category_summary.columns.values]

In [74]:
trs_category_summary = trs_category_summary.reset_index()

In [76]:
trs_category_summary.to_csv("../input/trs_category_summary.csv", index=False)