In [1]:
import numpy as np
import pandas as pd

/Users/naoki/.pyenv/versions/3.6.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/Users/naoki/.pyenv/versions/3.6.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

In [2]:
h_trs = pd.read_csv("../input/historical_transactions.csv", usecols=["card_id"])
n_trs = pd.read_csv("../input/new_merchant_transactions.csv", usecols=["card_id"])

In [10]:
df_h_trs_index = h_trs.reset_index().groupby("card_id")["index"].min().reset_index()
df_h_trs_index.columns = ["card_id", "h_trs_index"]

In [11]:
df_n_trs_index = n_trs.reset_index().groupby("card_id")["index"].min().reset_index()
df_n_trs_index.columns = ["card_id", "n_trs_index"]

In [12]:
df_trs_index = pd.merge(df_h_trs_index, df_n_trs_index, on="card_id", how="left")

In [15]:
df_trs_index = df_trs_index.sort_values(by="h_trs_index").reset_index(drop=True)
df_trs_index

                card_id  h_trs_index  n_trs_index
0       C_ID_4e6213e9bc            0    1905835.0
1       C_ID_5037ff576e          400    1865311.0
2       C_ID_0e171c1b48          518    1139995.0
3       C_ID_48fb13e70f          797    1955361.0
4       C_ID_fc8e41b9cf          877    1605082.0
5       C_ID_b02e55aa9d         1119    1410645.0
6       C_ID_b271e7ab60         1272    1918880.0
7       C_ID_4bed29d75c         1357    1684993.0
8       C_ID_93d201f55f         1443     919771.0
9       C_ID_3fff3df454         1663    1137199.0
10      C_ID_3898518baa         2184    1211488.0
11      C_ID_058b254a5b         2325     511279.0
12      C_ID_a9af70f52d         2812    1318765.0
13      C_ID_d3ec4a9f31         3038    1669545.0
14      C_ID_d244d8976d         3105     912188.0
15      C_ID_55aa6d6d5e         3390    1944574.0
16      C_ID_76ac7d7a48         3788     539005.0
17      C_ID_b45d4d37b1         3968     627811.0
18      C_ID_3da75e85ea         4379    1400481.0
19      C_ID_21117571cf         5204    1883746.0
20      C_ID_3917d75318         5430    1522984.0
21      C_ID_198914cf94         5682    1874903.0
22      C_ID_0d6b8c2d0f         6365      34340.0
23      C_ID_ad99f08d4c         6401     173851.0
24      C_ID_e5f5fcf6e7         6587    1727339.0
25      C_ID_12b7811978         6821          NaN
26      C_ID_72b66c75ad         6862     694027.0
27      C_ID_190bd090c9         7074    1925549.0
28      C_ID_25236b70f6         7109    1940179.0
29      C_ID_536bff298a         7659          NaN
...                 ...          ...          ...
325510  C_ID_564f9f299e     29112255          NaN
325511  C_ID_73e2938132     29112260    1107307.0
325512  C_ID_93f8262c97     29112266    1943860.0
325513  C_ID_1ac3ef2826     29112269    1745019.0
325514  C_ID_fc329a33d3     29112273    1470443.0
325515  C_ID_26110c46b5     29112278    1921254.0
325516  C_ID_6e6792da07     29112282          NaN
325517  C_ID_fa52d9db17     29112286     570744.0
325518  C_ID_fbf62043ea     29112289    1956988.0
325519  C_ID_36715dcad7     29112292    1389540.0
325520  C_ID_acee1fd6dd     29112296    1875541.0
325521  C_ID_82fcec3e6c     29112303    1826435.0
325522  C_ID_5a397de34c     29112306      26460.0
325523  C_ID_50149d8473     29112310     622494.0
325524  C_ID_4fe4bff0a8     29112313     848397.0
325525  C_ID_d4848aff3a     29112316          NaN
325526  C_ID_7e868f2655     29112319    1497791.0
325527  C_ID_2022979d38     29112322     466145.0
325528  C_ID_f7ba75a575     29112327          NaN
325529  C_ID_e43fce4842     29112330     910533.0
325530  C_ID_112832329d     29112333    1327491.0
325531  C_ID_2a8874827b     29112335    1780266.0
325532  C_ID_5c356aa384     29112337     911534.0
325533  C_ID_f9f906a4a2     29112340          NaN
325534  C_ID_5cf3187742     29112343    1239332.0
325535  C_ID_803aa0aed4     29112346     874033.0
325536  C_ID_62df280b20     29112349    1780198.0
325537  C_ID_e49b1996b0     29112353    1881949.0
325538  C_ID_2863d2fa95     29112356          NaN
325539  C_ID_5c240d6e3c     29112358     836527.0

[325540 rows x 3 columns]

In [17]:
df_trs_index.to_csv("../input/trs_index_min.csv", index=False)